# -*- coding: utf-8 -*-
"""XGAN-WBC-RVL-FVL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPbFLHGU6ohZiUo6xHg_oC23mylIYiC6
"""

from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Flatten, Activation,Input
from keras import optimizers
import pandas as pd
from sklearn.preprocessing import StandardScaler
from keras.optimizers import SGD,Adam
import numpy
from sklearn import svm
from sklearn.neighbors import NearestNeighbors
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.impute import SimpleImputer
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.metrics import roc_curve
from imblearn.under_sampling import RandomUnderSampler
import random
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import itertools
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.over_sampling import BorderlineSMOTE
from imblearn.over_sampling import RandomOverSampler

import csv
import pickle
OPTIMIZER = Adam(lr=0.002, decay=8e-9)








cancer_data = np.genfromtxt(
 fname ='breast-cancer-wisconsin.data', delimiter= ',', dtype= float)

cancer_data = np.delete(arr = cancer_data, obj= 0, axis = 1)
x = cancer_data[:,range(0,9)]
w = cancer_data[:,9]
w = numpy.array(w).astype('int')

imp = SimpleImputer(missing_values=np.nan, strategy='mean')
x = imp.fit_transform(x)

for i in range(0, len(x)):

    if (w[i] == 4):
        w[i]=1

    else:
        w[i] = 0


amount_scaler = StandardScaler().fit(x[:])
x[:] = amount_scaler.transform(x[:])





dim = x.shape




ntrain=0
def discriminator():
    model= Sequential()
    model.add(Dense(20, input_dim=9))


    model.add(Dense(8))
    model.add(Dense(1, activation='sigmoid'))

    return model


def regression():
    model = Sequential()
    model.add(Dense(36, input_dim=9))
    model.add(Dense(18))
    model.add(Dense(9, activation='sigmoid'))

    return model


def stacked():
    disc.trainable = False

    model = Sequential()
    model.add(reg)
    model.add(disc)

    return model



reg= regression()
reg.compile(loss='binary_crossentropy', optimizer=OPTIMIZER)
disc=discriminator()
disc.compile(loss='binary_crossentropy', optimizer=OPTIMIZER,metrics=['accuracy'])
stack=stacked()
stack.compile(loss='binary_crossentropy', optimizer=OPTIMIZER,metrics=['accuracy'])


c1=0
c2=0

for i in range(0, dim[0]):

            if (w[i] == 1):
                
                c1 = c1 + 1
            else:
                
                c2 = c2 + 1


majority = numpy.zeros((c2, 9), dtype=numpy.float)
minority = numpy.zeros((c1, 9), dtype=numpy.float)

c1 = 0
c2 = 0
for i in range(0, len(x)):
     if (w[i] == 1):
                minority[c1] = (x[i])
                c1 = c1 + 1
     else:
                majority[c2] = (x[i])
                c2 = c2 + 1

def train(X_train,disc, epochs=100, batch=64, save_interval=200):
            autoencoder =''
            autoencoder2 =''
            input_img = Input(shape=(9,))
            encoded = Dense(6, activation='relu')(input_img)
            encoded = Dense(5, activation='relu')(encoded)
            encoded = Dense(3, activation='relu')(encoded)

            decoded = Dense(5, activation='relu')(encoded)
            decoded = Dense(6, activation='relu')(decoded)
            decoded = Dense(9, activation='sigmoid')(decoded)

            autoencoder = Model(input_img, decoded)
            autoencoder2 = Model(input_img, decoded)
            autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')
            autoencoder2.compile(optimizer='adadelta', loss='binary_crossentropy')
            epoch = []
            for cnt in range(epochs):
                ## train discriminator
                legit_images = X_train
                gen_noise = np.random.uniform(0, 1, size=[len(minority), 9])
                syntetic_images = reg.predict(gen_noise)
                print(syntetic_images.shape)
                # print(legit_images.)

                x_combined_batch = np.concatenate((legit_images, syntetic_images))
                y_combined_batch = np.concatenate(
                    (np.ones((len(legit_images), 1)), np.zeros((len(syntetic_images), 1))))

                d_loss = disc.train_on_batch(x_combined_batch, y_combined_batch)
                d_loss = disc.train_on_batch(x_combined_batch, y_combined_batch)
                

                # train generator
                noise = np.random.normal(0, 1, (10, 9))
                y_mislabled = np.ones((10, 1))
                g_loss = stack.train_on_batch(noise, y_mislabled)


                history2=autoencoder.fit(syntetic_images ,syntetic_images,
                epochs=1,
                batch_size=256,
                shuffle=True,verbose=0,
                validation_data=(legit_images, legit_images))
            

                history20=autoencoder2.fit(legit_images ,legit_images,
                epochs=1,
                batch_size=256,
                shuffle=True,verbose=0,
                validation_data=(syntetic_images, syntetic_images))


                val_loss = history2.history['val_loss']
                val_loss2 = history20.history['val_loss']
                
                print('RVL : ' + str(val_loss2[len( val_loss)-1]) + '---' + 'FVL : ' + str(val_loss[len( val_loss)-1]) )
                epoch.append(cnt)
                #print('epoch: %d, [Discriminator :: d_loss: %f], [ Generator :: loss: %f]' % (cnt, dloss[0], g_loss))
                #print('Epoch : ' + str(cnt) + '----' + str(d_loss[0]) + '----' + str(g_loss[0]))


            




train(minority,disc)